name: Deep Into Nebula building

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    container:
      image: rust
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: requirements
        run: |
          cargo install mdbook
        shell: bash
      - name: building
        run: |
          mdbook build
        shell: bash
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: book/ # The folder the action should deploy.
        shell: bash
