name: Deep Into Nebula building

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    container:
      image: rust
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: requirements
        run: |
          cargo install mdbook
        shell: bash
      - name: building
        run: |
          mdbook build
        shell: bash
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: book
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
